In [1]:
from scipy.optimize import linprog

In [2]:
import numpy as np

import math

# Environment Setting

In [3]:
# Number of Robot
nr = 3

RobotsID = [1,2,3,4] # Robots ID during the missino

In [6]:
# Robot Position

p = np.array([[0,1,1,2],[0,1,1,2]])
print(p)

# px = np.zeros(nr,dtype=int)
# px= np.array([0,-2,-2])
# print(px)


# # py = np.zeros(nr,dtype=int)
# py= np.array([0,0,2])
# print(py)

TypeError: Field elements must be 2- or 3-tuples, got '0'

In [4]:
# Number of Target
nt = 8

In [5]:
# Matrix of Robot Velocity
v = np.array([0.2,0.4,0.4])
print(v)

[0.2 0.4 0.4]


In [6]:
# Matrix of Robot Battery Level
b = np.array([3,1,1])
print(b)

[3 1 1]


In [7]:
# Matrix of Robot Battery Consumption
w = np.array([1,2,2])
print(w)

[1 2 2]


In [9]:
# Target X - Y Axis Location

qx = np.array([-5,-9,-5,-9,5,9,5,9]) 

qy = np.array([-5,-6,5,6,-5,-6,5,6])

print(qx)
print(qy)

[-5 -9 -5 -9  5  9  5  9]
[-5 -6  5  6 -5 -6  5  6]


In [10]:
# Matrix d represents distance from robot-i to target-j
d =  np.zeros([nr,nt],dtype=float)
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
# Manhattan Distance
""" 
for i in range (1,nr+1):
    for j in range (1,nt+1):
        d[i-1,j-1] = abs(qy[j-1]-py[i-1]) + abs(qx[j-1]-px[i-1])
"""

# Euclidian Distance

for i in range (1,nr+1):
    for j in range (1,nt+1):
        d[i-1,j-1] = math.sqrt(pow(qy[j-1]-py[i-1],2)+pow(qx[j-1]-px[i-1],2))


print(d)



[[ 7.07106781 10.81665383  7.07106781 10.81665383  7.07106781 10.81665383
   7.07106781 10.81665383]
 [ 5.83095189  9.21954446  5.83095189  9.21954446  8.60232527 12.52996409
   8.60232527 12.52996409]
 [ 7.61577311 10.63014581  4.24264069  8.06225775  9.89949494 13.60147051
   7.61577311 11.70469991]]


In [12]:
# Matrix t which represents time required for robot i to travel to target j

t = d / v.transpose()[:,None]
print(t)

[[35.35533906 54.08326913 35.35533906 54.08326913 35.35533906 54.08326913
  35.35533906 54.08326913]
 [14.57737974 23.04886114 14.57737974 23.04886114 21.50581317 31.32491022
  21.50581317 31.32491022]
 [19.03943276 26.57536453 10.60660172 20.15564437 24.74873734 34.00367627
  19.03943276 29.26174978]]


In [13]:
# Matrix E (Represents energy used related to distance)

e  = d * w.transpose()[:,None]
print(e)

[[ 7.07106781 10.81665383  7.07106781 10.81665383  7.07106781 10.81665383
   7.07106781 10.81665383]
 [11.66190379 18.43908891 11.66190379 18.43908891 17.20465053 25.05992817
  17.20465053 25.05992817]
 [15.23154621 21.26029163  8.48528137 16.1245155  19.79898987 27.20294102
  15.23154621 23.40939982]]


In [14]:
# Matrix Importance Phi

phi_j = np.array([1,1,1,1,1,1,1,1])
print(phi_j)

[1 1 1 1 1 1 1 1]


# Objective Function

In [15]:
# Define Matrix g as Matrix for Cost Function
g = np.zeros([nr,nt,nt],dtype=float)
print(g)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [16]:
for i in range (1,nr+1):
    for j in range (1,nt+1):
        for k in range (1,nt+1):
            #[i-1k] = 50*(phi_j[j]*t[i,j]*(k+1)) #- (phi_j[j]*(k+1)*(b[i]-e[i,j]))
            #[i-1,j-1,k-1] = 100*i + 10*j + k
            g[i-1,j-1,k-1] = 50*(phi_j[j-1]*t[i-1,j-1]*k)
print(g)

f = g.flatten()

print(f)
      

[[[ 1767.76695297  3535.53390593  5303.3008589   7071.06781187
    8838.83476483 10606.6017178  12374.36867076 14142.13562373]
  [ 2704.1634566   5408.3269132   8112.49036979 10816.65382639
   13520.81728299 16224.98073959 18929.14419619 21633.30765278]
  [ 1767.76695297  3535.53390593  5303.3008589   7071.06781187
    8838.83476483 10606.6017178  12374.36867076 14142.13562373]
  [ 2704.1634566   5408.3269132   8112.49036979 10816.65382639
   13520.81728299 16224.98073959 18929.14419619 21633.30765278]
  [ 1767.76695297  3535.53390593  5303.3008589   7071.06781187
    8838.83476483 10606.6017178  12374.36867076 14142.13562373]
  [ 2704.1634566   5408.3269132   8112.49036979 10816.65382639
   13520.81728299 16224.98073959 18929.14419619 21633.30765278]
  [ 1767.76695297  3535.53390593  5303.3008589   7071.06781187
    8838.83476483 10606.6017178  12374.36867076 14142.13562373]
  [ 2704.1634566   5408.3269132   8112.49036979 10816.65382639
   13520.81728299 16224.98073959 18929.14419619 

# Equality Constraint 

In [17]:
# Equality Constraint

a1 = np.hstack((np.ones(nt,dtype=int),np.zeros(nt*(nt-1),dtype=int)))

a2 = np.tile(a1,nr)

a3 = np.roll(a2,nt)



temp1 = np.roll(a2,-nt)
Aeq = np.array([]).reshape(0,(nr*nt*nt))

for j in range (1,nt+1):
    temp1 = np.roll(temp1,nt)
    Aeq = np.vstack([Aeq,temp1])
    
print(Aeq)

beq = np.ones(nt)
print(beq)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1.]


# Inequality Constraint

In [18]:
# Inequality Constraint

b1 = np.identity(nt)

b2 = np.tile(b1,nt)

b3 = np.hstack((b2,np.zeros((nt,(nt*nt*(nr-1))))))

b4 = np.roll(b3,nt*nt)



temp2 = np.roll(b3,-nt*nt)
A = np.array([]).reshape(0,(nr*nt*nt))

for i in range (1,nr+1):
    temp2 = np.roll(temp2,nt*nt)
    A = np.vstack([A,temp2])
    
print(A)

b = np.ones(nr*nt,dtype=int)
print(b)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


# Lower & Upper Bound

In [19]:
lb = np.zeros(nr*nt*nt,dtype=int)
ub = np.array([]).reshape(0,(nr*nt*nt))

In [20]:
res =  linprog(f,A_ub = A, b_ub = b, A_eq = Aeq, b_eq = beq)
print(res)
print(res.x)

     con: array([-2.33368880e-13, -4.35651515e-13, -4.87387908e-13, -6.97442104e-13,
       -4.90274488e-13, -4.15223411e-13, -4.33875158e-13, -4.73177053e-13])
     fun: 16281.392722822306
 message: 'Optimization terminated successfully.'
     nit: 10
   slack: array([-1.29674049e-13,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        4.77395901e-15, -1.31006317e-13, -4.70734562e-14,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
       -1.45439216e-13, -2.28483898e-13,  4.41868764e-14,  2.16615614e-12,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00])
  status: 0
 success: True
       x: array([6.97717645e-14, 7.33701941e-14, 2.51236546e-14, 1.65127561e-14,
       9.30062430e-15, 1.24778197e-14, 1.13009239e-14, 4.08483287e-15,
       8.06541882e-14, 3.88828985e-14, 1.51213134e-14, 1.00471316e-14,
       6.81992180e-15, 7.11573188e-1

/home/mhanif/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: OptimizeWarning: Solving system with option 'cholesky':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'cholesky' to False.
  """Entry point for launching an IPython kernel.
/home/mhanif/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: OptimizeWarning: Solving system with option 'sym_pos':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'sym_pos' to False.
  """Entry point for launching an IPython kernel.
/home/mhanif/.local/lib/python3.6/site-packages/scipy/optimize/_linprog_ip.py:116: LinAlgWarning: Ill-conditioned matrix (rcond=2.56366e-20): result may not be accurate.
  return sp.linalg.solve(M, r, sym_pos=sym_pos)


In [21]:
results = np.reshape(res.x,(nr,nt,nt))
results = np.around(results, decimals = 0)
#results = results.astype(int)
print(results)


[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]]]


In [22]:
rfl = np.zeros((nr,nt))

for i in range (1,nr+1):
    for j in range (1,nt+1):
        for k in range (1,nt+1):
            if results[i-1,j-1,k-1] == 1:
                rfl[i-1,k-1] = j

print(rfl)

[[5. 0. 0. 0. 0. 0. 0. 0.]
 [6. 2. 1. 0. 0. 0. 0. 0.]
 [8. 4. 7. 3. 0. 0. 0. 0.]]
